services:
  db:
    image: postgres
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    build: backend/
    image: kassensystem-backend:latest
    hostname: kassensystem-backend
    environment:
      - DJANGO_DEBUG=true
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@admin.ch
      - DJANGO_SUPERUSER_PASSWORD=admin
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: frontend/
    image: kassensystem-frontend:latest
    environment:
      - CHOKIDAR_USEPOLLING=true
      - BACKEND_ADDRESS=http://kassensystem_backend:8080
    volumes:
      - type: bind
        source: ./frontend/
        target: /app
      - type: volume
        source: node-modules
        target: /app/node_modules
    ports:
      - "3000:3000"

networks: 
  default:
    name: kassensystem

volumes:
  node-modules:
  db-data:
