# Generated by Django 4.0.5 on 2022-07-31 15:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(null=True)),
                ("name", models.CharField(max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Manager",
                "verbose_name_plural": "Managers",
            },
        ),
        migrations.CreateModel(
            name="Waiter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(null=True)),
                ("name", models.CharField(max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Waiter",
                "verbose_name_plural": "Waiters",
            },
        ),
    ]
