# Generated by Django 4.0.5 on 2022-07-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_waiter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waiter',
            options={'verbose_name': 'Waiter', 'verbose_name_plural': 'Waiters'},
        ),
        migrations.AddField(
            model_name='waiter',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
