openapi: 3.0.3
info:
  title: Point of Sale API
  version: 1.0.0
  description: point of sale system
paths:
  /api/v1/pos/order/:
    get:
      operationId: pos_order_list
      tags:
      - pos
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
          description: ''
    post:
      operationId: pos_order_create
      tags:
      - pos
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Order'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Order'
      security:
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: ''
  /api/v1/product-catalogue/category/:
    get:
      operationId: product_catalogue_category_list
      tags:
      - product-catalogue
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
          description: ''
    post:
      operationId: product_catalogue_category_create
      tags:
      - product-catalogue
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Category'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Category'
        required: true
      security:
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
          description: ''
  /api/v1/product-catalogue/category/{id}/:
    get:
      operationId: product_catalogue_category_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - product-catalogue
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
          description: ''
    put:
      operationId: product_catalogue_category_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - product-catalogue
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Category'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Category'
        required: true
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
          description: ''
    patch:
      operationId: product_catalogue_category_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - product-catalogue
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedCategory'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedCategory'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedCategory'
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
          description: ''
    delete:
      operationId: product_catalogue_category_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - product-catalogue
      security:
      - cookieAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/product-catalogue/menu-item/:
    get:
      operationId: product_catalogue_menu_item_list
      tags:
      - product-catalogue
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MenuItem'
          description: ''
    post:
      operationId: product_catalogue_menu_item_create
      tags:
      - product-catalogue
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MenuItem'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MenuItem'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MenuItem'
        required: true
      security:
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuItem'
          description: ''
  /api/v1/product-catalogue/menu-item/{id}/:
    get:
      operationId: product_catalogue_menu_item_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - product-catalogue
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuItem'
          description: ''
    put:
      operationId: product_catalogue_menu_item_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - product-catalogue
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MenuItem'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MenuItem'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MenuItem'
        required: true
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuItem'
          description: ''
    patch:
      operationId: product_catalogue_menu_item_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - product-catalogue
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedMenuItem'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedMenuItem'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedMenuItem'
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuItem'
          description: ''
    delete:
      operationId: product_catalogue_menu_item_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - product-catalogue
      security:
      - cookieAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/product-catalogue/sales-tax/:
    get:
      operationId: product_catalogue_sales_tax_list
      tags:
      - product-catalogue
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SalesTax'
          description: ''
    post:
      operationId: product_catalogue_sales_tax_create
      tags:
      - product-catalogue
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SalesTax'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SalesTax'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SalesTax'
        required: true
      security:
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SalesTax'
          description: ''
  /api/v1/product-catalogue/sales-tax/{id}/:
    get:
      operationId: product_catalogue_sales_tax_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - product-catalogue
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SalesTax'
          description: ''
    put:
      operationId: product_catalogue_sales_tax_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - product-catalogue
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SalesTax'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SalesTax'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SalesTax'
        required: true
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SalesTax'
          description: ''
    patch:
      operationId: product_catalogue_sales_tax_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - product-catalogue
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedSalesTax'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedSalesTax'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedSalesTax'
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SalesTax'
          description: ''
    delete:
      operationId: product_catalogue_sales_tax_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - product-catalogue
      security:
      - cookieAuth: []
      responses:
        '204':
          description: No response body
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 50
      required:
      - id
      - name
    MenuItem:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 50
        price:
          type: integer
      required:
      - id
      - name
      - price
    MenuItemPublic:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          readOnly: true
        price:
          type: integer
          readOnly: true
      required:
      - id
      - name
      - price
    Order:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        menu_item:
          allOf:
          - $ref: '#/components/schemas/MenuItemPublic'
          readOnly: true
      required:
      - id
      - menu_item
    PatchedCategory:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 50
    PatchedMenuItem:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 50
        price:
          type: integer
    PatchedSalesTax:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        rate:
          type: string
          format: decimal
          pattern: ^-?\d{0,2}(?:\.\d{0,2})?$
    SalesTax:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        rate:
          type: string
          format: decimal
          pattern: ^-?\d{0,2}(?:\.\d{0,2})?$
      required:
      - id
      - name
      - rate
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
