# Generated by Django 4.0.5 on 2022-08-06 14:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("product_catalogue", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="valid_to",
            field=models.DateTimeField(
                default=datetime.datetime(9999, 12, 31, 22, 59, 59, tzinfo=utc)
            ),
        ),
        migrations.AlterField(
            model_name="salestax",
            name="valid_to",
            field=models.DateTimeField(
                default=datetime.datetime(9999, 12, 31, 22, 59, 59, tzinfo=utc)
            ),
        ),
    ]
