# Generated by Django 4.0.5 on 2022-06-26 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalogue', '0002_remove_menuitem_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59)),
        ),
        migrations.AlterField(
            model_name='salestax',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59)),
        ),
    ]
