# Generated by Django 4.0.5 on 2022-07-16 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalogue', '0001_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='menu_items',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalogue.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.order')),
            ],
        ),
    ]
