# Generated by Django 4.0.5 on 2022-06-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalogue', '0004_remove_menuitem_category_menuitem_category'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='menu_items',
            field=models.ManyToManyField(blank=True, to='product_catalogue.menuitem'),
        ),
    ]
