# Generated by Django 4.0.5 on 2022-06-26 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pos.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='pos.paymentmethod'),
        ),
    ]
