# Generated by Django 4.0.5 on 2022-07-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
