# Generated by Django 4.1 on 2022-08-20 15:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SalesTax",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("valid_from", models.DateTimeField(auto_now_add=True)),
                (
                    "valid_to",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999, 12, 31, 23, 59, 59, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("valid_from", models.DateTimeField(auto_now_add=True)),
                (
                    "valid_to",
                    models.DateTimeField(
                        default=datetime.datetime(
                            9999, 12, 31, 23, 59, 59, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="read.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
