on:
  release:
    types: [created]

name: Deploy Dev Environment

env:
  CONTAINER_NAME: kassensystem

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build ./backend/ -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
            
        - name: Set Web App ACR authentication
          uses: Azure/appservice-settings@v1
          with:
           app-name: 'app-capital-pos'
           app-settings-json: |
             [
                 {
                     "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
                     "value": "${{ secrets.REGISTRY_PASSWORD }}",
                     "slotSetting": false
                 },
                 {
                     "name": "DOCKER_REGISTRY_SERVER_URL",
                     "value": "${{ secrets.REGISTRY_LOGIN_SERVER }}",
                     "slotSetting": false
                 },
                 {
                     "name": "DOCKER_REGISTRY_SERVER_USERNAME",
                     "value": "${{ secrets.REGISTRY_USERNAME }}",
                     "slotSetting": false
                 }
             ]
            
        - uses: azure/webapps-deploy@v2
          with:
            app-name: 'app-capital-pos'
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}'
