name: Django CI

on:
  push:
    branches: [ "main" ]
    paths:
      - backend/**
  pull_request:
    branches: [ "main" ]
    paths:
      - backend/**

env:
  PYTHON_VERSION: "3.10"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Set up cache
      uses: actions/cache@v2
      id: cached-poetry-dependencies
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies
      run: |
        cd backend
        poetry install --no-interaction
        PATH=.venv/bin:$PATH
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
    - name: Run Tests
      run: |
        cd backend/django-server
        python manage.py test
